# Generated by Django 5.2.12 on 2026-03-27 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("request_data", models.JSONField()),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("image_file", models.FileField(blank=True, null=True, upload_to="jobs/%Y/%m/")),
                ("video_file", models.FileField(blank=True, null=True, upload_to="jobs/%Y/%m/")),
                ("vram_peak_mb", models.FloatField(blank=True, null=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255, null=True)),
                ("checkpoint_path", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "jobs_generationjob",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="jobs_genera_status_a5337a_idx"
                    )
                ],
            },
        ),
    ]
